/*
 * Protobuf TWS API
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package protobuf;

import "Contract.proto";

option java_outer_classname = "ExerciseOptionsRequestProto";
option java_package = "io.github.bjconlan.ibkr.proto";
option csharp_namespace = "IBApi.protobuf";

message ExerciseOptionsRequest {
    optional int32 orderId = 1; // The API client's order id.
    optional Contract contract = 2; // Contract object containing defining characteristics for ticker.
    optional int32 exerciseAction = 3; // Set to 1 to exercise the option, set to 2 to let the option lapse.
    optional int32 exerciseQuantity = 4; // Number of contracts to be exercised.
    optional string account = 5; // The IBKR account identifier to affiliate the request with.
    optional bool override = 6; // Indicate if the default options exercise behavior should be overwritten.
    optional string manualOrderTime = 7; // Used by brokers and advisors when manually entering an order request. Format should be "YYYYMMDD-HH:mm:ss" using UTC as the timezone value.
    optional string customerAccount = 8; // Required for Nondisclosed Omnibus Accounts. A unique identifier for each account within the Omnibus structure to signify the account holder being traded. Best practice (Not Required): clients should look to hash this value, using something along the lines of 5 digits of SHA1 of the account number. This should not be implemented for non-omnibus accounts.
    optional bool professionalCustomer = 9; // true indicates account represents an institutional or professional trader.
}
