/*
 * Protobuf TWS API
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package protobuf;

import "TickAttribLast.proto";

option java_outer_classname = "HistoricalTickLastProto";
option java_package = "io.github.bjconlan.ibkr.proto";
option csharp_namespace = "IBApi.protobuf";

message HistoricalTickLast {
    optional int64 time = 1; // The UNIX timestamp of the historical tick.
	optional TickAttribLast tickAttribLast = 2; // Tick attribs of historical last tick.
    optional double price = 3; // The last price of the historical tick.
    optional string size = 4; // The last size of the historical tick.
    optional string exchange = 5; // The source exchange of the historical tick.
    optional string specialConditions = 6; // The conditions of the historical tick. Refer to [Trade Conditions](https://www.interactivebrokers.com/en/index.php?f=7235) page for more details.
}
