/*
 * Protobuf TWS API
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package protobuf;

import "Contract.proto";

option java_outer_classname = "ScannerDataElementProto";
option java_package = "io.github.bjconlan.ibkr.proto";
option csharp_namespace = "IBApi.protobuf";

message ScannerDataElement {
    optional int32 rank = 1; // Position of the sorted scanner results.
	optional Contract contract = 2; // Contract object containing defining characteristics for ticker.
    optional string marketName = 3; // Instrument's local name.
    optional string distance = 4; // Internal use only.
    optional string benchmark = 5; // Always returns an empty string.
    optional string projection = 6; // Internal use only.
    optional string comboKey = 7; // Describes the combo legs when the scanner is returning EFP.
}
