/*
 * Protobuf TWS API
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package protobuf;

import "UpdateConfigWarning.proto";

option java_outer_classname = "UpdateConfigResponseProto";
option java_package = "io.github.bjconlan.ibkr.proto";
option csharp_namespace = "IBApi.protobuf";

message UpdateConfigResponse {
    optional int32 reqId = 1; // Unique request identifier used for tracking across EWrapper.
    optional string status = 2; // Current status of the order.
    optional string message = 3; // The news bulletin context.
    repeated string changedFields = 4; // All fields changed from the UpdateConfigRequest.
    repeated string errors = 5; // Proto path that failed to update.
    repeated UpdateConfigWarning warnings = 6; // Object containing detailed warnings about setting modification.
}
