/*
 * Protobuf TWS API
 *
 * Copyright (C) 2013-2026  Interactive Brokers LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package protobuf;

option java_outer_classname = "WshEventDataRequestProto";
option java_package = "io.github.bjconlan.ibkr.proto";
option csharp_namespace = "IBApi.protobuf";

message WshEventDataRequest {
    optional int32 reqId = 1; // Unique request identifier used for tracking across EWrapper.
    optional int32 conId = 2; // The unique IB contract identifier.
    optional string filter = 3; // The filter criteria used to determine which execution reports are returned.
    optional bool fillWatchlist = 4; // Automatically fill in values from your watchlist.
    optional bool fillPortfolio = 5; // Automatically fill in values from your portfolio.
    optional bool fillCompetitors = 6; // Automatically fill in competitor values of existing positions.
    optional string startDate = 7; // The earliest starting point of the request. Formatted as "YYYYMMDD-HH:mm:ss" to assume UTC or "YYYYMMDD HH:mm:ss TMZ".
    optional string endDate = 8; // Specify the end date of the event requests. Formatted as "YYYYMMDD".
    optional int32 totalLimit = 9; // Maximum number of WSH Events that may be returned.
}
